[build]
builder = "NIXPACKS"

[deploy]
startCommand = "pnpm start"
preDeployCommand = ["pnpm exec prisma migrate deploy"]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
