import { test, expect } from "@playwright/test";
import { join } from "node:path";

const MAILPIT = "http://127.0.0.1:55324";
// Generated by scripts/gen-fixture.ts before the run (avoids importing TS helpers
// through Playwright's loader).
const IGC_PATH = process.env.E2E_IGC ?? join(process.cwd(), "test/e2e/.fixture.igc");

type MailpitMsg = { ID: string; To?: { Address: string }[] };

/** Poll Mailpit for the latest message to an address and return its first link. */
async function getMagicLink(email: string): Promise<string> {
  for (let i = 0; i < 30; i++) {
    const res = await fetch(`${MAILPIT}/api/v1/messages?limit=30`);
    if (res.ok) {
      const data = await res.json();
      const msg = (data.messages as MailpitMsg[] | undefined)?.find((m) =>
        m.To?.some((t) => t.Address.toLowerCase() === email.toLowerCase()),
      );
      if (msg) {
        const full = await fetch(`${MAILPIT}/api/v1/message/${msg.ID}`).then((r) => r.json());
        const body: string = full.HTML || full.Text || "";
        const m = body.match(/https?:\/\/[^"'\s<>]+/);
        if (m) return m[0].replace(/&amp;/g, "&");
      }
    }
    await new Promise((r) => setTimeout(r, 1000));
  }
  throw new Error("magic link email never arrived");
}

test("sign up → upload → view → share → logged-out view", async ({ page, context }) => {
  const suffix = `${Date.now()}`;
  const email = `e2e_${suffix}@test.local`;
  const handle = `e2e${suffix}`.slice(0, 18);
  const igcPath = IGC_PATH;

  // 1. Request a magic link.
  await page.goto("/sign-in");
  await page.getByPlaceholder("you@example.com").fill(email);
  await page.getByRole("button", { name: /send magic link/i }).click();
  await expect(page.getByText(/check your email/i)).toBeVisible();

  // 2. Follow the magic link in the same browser context (PKCE verifier lives here).
  const link = await getMagicLink(email);
  await page.goto(link);

  // 3. Onboarding.
  await expect(page).toHaveURL(/\/onboarding/, { timeout: 15_000 });
  await page.locator('input[name="handle"]').fill(handle);
  await page.locator('input[name="display_name"]').fill("E2E Pilot");
  await page.getByRole("button", { name: /create my logbook/i }).click();
  await expect(page).toHaveURL(/\/logbook/, { timeout: 15_000 });

  // 4. Upload a flight.
  await page.goto("/upload");
  await page.locator('input[type="file"]').setInputFiles(igcPath);

  // 5. Land on the flight page with real metrics.
  await expect(page).toHaveURL(/\/flights\/[0-9a-f-]{36}/, { timeout: 30_000 });
  const flightUrl = page.url();
  await expect(page.getByText("Airtime")).toBeVisible();
  await expect(page.getByText("Max altitude")).toBeVisible();
  // Named-site reverse lookup: the seeded launch is identified.
  await expect(page.getByRole("heading", { name: "Mussel Rock" })).toBeVisible();

  // 6. Share it publicly.
  await page.getByRole("button", { name: /share flight/i }).click();
  await expect(page.getByText(/shared publicly/i)).toBeVisible({ timeout: 10_000 });

  // 7. A logged-out visitor can see the now-public flight.
  const anon = await context.browser()!.newContext();
  const anonPage = await anon.newPage();
  const res = await anonPage.goto(flightUrl);
  expect(res?.status()).toBe(200);
  await expect(anonPage.getByText("Airtime")).toBeVisible();
  await anon.close();
});
