import { test, expect, type Page } from "@playwright/test";
import { existsSync, readFileSync, rmSync } from "node:fs";
import { DEV_MAGIC_LINK_FILE as LINK_FILE } from "@/lib/dev-magic-link";
import { makeRealisticFlight } from "../igc/make-igc";
import { uploadFlight } from "./helpers";
import { PrismaClient } from "@prisma/client";

async function signUp(page: Page) {
  const handle = `import${Date.now()}`.slice(0, 18);
  rmSync(LINK_FILE, { force: true });
  await page.goto("/sign-in");
  await page.getByPlaceholder("you@example.com").fill(`${handle}@test.local`);
  await page.getByRole("button", { name: /send magic link/i }).click();
  await expect(page.getByRole("heading", { name: /check your email/i })).toBeVisible();
  await expect.poll(() => existsSync(LINK_FILE) && readFileSync(LINK_FILE, "utf8").startsWith("http")).toBe(true);
  await page.goto(readFileSync(LINK_FILE, "utf8").trim());
  await page.getByRole("button", { name: /keep me signed in/i }).click();
  await expect(page).toHaveURL(/\/onboarding/);
  await page.locator('input[name="handle"]').fill(handle);
  await page.locator('input[name="display_name"]').fill("Historic Pilot");
  await page.getByRole("button", { name: /create my logbook/i }).click();
  await expect(page).toHaveURL(/\/logbook/);
  return handle;
}

test("exports the full logbook as CSV and original IGC ZIP from desktop and mobile", async ({ page }) => {
  const handle = await signUp(page);
  const db = new PrismaClient();
  const raw = Buffer.from("AXXX\r\nHFDTE120626\r\nGOriginal signature\r\n");
  try {
    const profile = await db.profile.findUniqueOrThrow({ where: { handle } });
    await db.flight.create({ data: { ownerId: profile.id, status: "failed", flightDate: new Date("2026-06-12"), data: { create: { rawIgc: raw } } } });
    await db.flight.create({ data: { ownerId: profile.id, recordingKind: "logbook", source: "manual_entry", status: "ready", flightDate: new Date("2000-01-01"), notes: "Manual flight" } });
    await page.reload();
    await page.waitForFunction(id => sessionStorage.getItem(`leaf-logbook-filters:v1:${id}`) !== null, profile.id);
    await page.getByRole("button", { name: "Select Dates" }).click();
    await page.getByLabel("From", { exact: true }).fill("2099-01-01");
    await expect(page.getByText("No flights match these filters.")).toBeVisible();
    await expect(page.getByRole("button", { name: "Export logbook", exact: true })).toHaveCount(0);
    await page.goto("/settings");
    await page.getByRole("button", { name: "Export logbook", exact: true }).click();
    const csvDownload = page.waitForEvent("download");
    await page.getByRole("link", { name: /Download CSV/ }).click();
    const csv = await csvDownload;
    expect(csv.suggestedFilename()).toMatch(/^leaf-log-logbook-.*\.csv$/);
    expect(await csv.failure()).toBeNull();
    const text = readFileSync((await csv.path())!, "utf8");
    expect(text).toContain('"igc_filename"');
    expect(text).toContain("Manual flight");
    expect(text).toContain("flight-2026-06-12-");
    await page.keyboard.press("Escape");
    await expect(page.getByRole("button", { name: "Export logbook", exact: true })).toBeFocused();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole("button", { name: "Export logbook", exact: true }).click();
    const zipLink = page.getByRole("link", { name: /Download IGC ZIP/ });
    await expect(zipLink).toBeInViewport();
    for (const width of [320, 480, 639, 640, 768, 390]) {
      await page.setViewportSize({ width, height: 844 });
      const importBox = await page.getByRole("link", { name: "Import logbook", exact: true }).boundingBox();
      const exportBox = await page.getByRole("button", { name: "Export logbook", exact: true }).boundingBox();
      expect(Math.abs(importBox!.y - exportBox!.y)).toBeLessThan(1);
      expect(importBox!.x + importBox!.width).toBeLessThan(exportBox!.x);
      const box = await zipLink.boundingBox();
      expect(box!.x).toBeGreaterThanOrEqual(0);
      expect(box!.x + box!.width).toBeLessThanOrEqual(width);
    }
    await page.screenshot({ path: "test-results/logbook-export-mobile.png", fullPage: true });
    const zipDownload = page.waitForEvent("download");
    await zipLink.click();
    const zip = await zipDownload;
    expect(zip.suggestedFilename()).toMatch(/^leaf-log-igc-.*\.zip$/);
    expect(await zip.failure()).toBeNull();
    const { ZipReader, Uint8ArrayReader, Uint8ArrayWriter } = await import("@zip.js/zip.js");
    const reader = new ZipReader(new Uint8ArrayReader(readFileSync((await zip.path())!)), { useWebWorkers: false });
    const entries = await reader.getEntries();
    expect(entries).toHaveLength(1);
    const entry = entries[0];
    if (entry.directory) throw new Error("Unexpected directory");
    expect(Buffer.from(await entry.getData(new Uint8ArrayWriter(), { checkSignature: true }))).toEqual(raw);
    expect(text).toContain(entry.filename);
    await reader.close();
    await page.goto("/settings");
    await page.getByRole("button", { name: "Export logbook", exact: true }).click();
    const settingsCsv = page.getByRole("link", { name: /Download CSV/ });
    await expect(settingsCsv).toBeVisible();
    const settingsBox = await settingsCsv.boundingBox();
    expect(settingsBox!.x).toBeGreaterThanOrEqual(0);
    expect(settingsBox!.x + settingsBox!.width).toBeLessThanOrEqual(390);
  } finally {
    await db.$disconnect();
  }
});

test("manual location search moves the map before choosing exact coordinates, including on mobile", async ({ page }) => {
  await signUp(page);
  await page.route("https://tiles.openfreemap.org/styles/liberty", route => route.fulfill({ json: { version: 8, sources: {}, layers: [] } }));
  let searches = 0;
  await page.route("https://api.maptiler.com/geocoding/**", route => {
    searches++;
    return route.fulfill({ json: { features: [{ id: "annecy", place_name: "Annecy, Haute-Savoie, France", center: [6.13, 45.9], bbox: [6.06, 45.85, 6.17, 45.95] }] } });
  });
  await page.goto("/upload");
  const introduction = page.locator("main > p");
  await expect(introduction).toHaveText("Drop an .igc file from your Leaf (or any flight recorder). We'll parse it and build your flight page. Flights are private until you choose to share them.");
  await expect(introduction.locator("code, span")).toHaveCount(0);
  await expect(page.getByLabel("Flight date", { exact: true })).toBeEnabled();
  await page.getByLabel("Flight date", { exact: true }).fill("2024-07-12");
  await page.getByLabel("Flying site name", { exact: true }).fill("Memory Hill");
  await page.getByText("Site location", { exact: true }).click();
  await page.getByRole("button", { name: "Choose on map", exact: true }).click();
  const search = page.getByRole("searchbox", { name: "Find a place" });
  await search.fill("Annecy France");
  expect(searches).toBe(0);
  await search.press("Enter");
  const result = page.getByRole("button", { name: "Annecy, Haute-Savoie, France", exact: true });
  await expect(result).toBeVisible();
  expect(searches).toBe(1);
  await expect(page).toHaveURL(/\/upload$/);
  for (const width of [320, 390, 768]) {
    await page.setViewportSize({ width, height: 844 });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await search.scrollIntoViewIfNeeded();
    await expect(search).toBeInViewport();
    await expect(page.getByRole("button", { name: "Search", exact: true })).toBeInViewport();
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await search.scrollIntoViewIfNeeded();
  await page.screenshot({ path: "test-results/manual-place-search-mobile.png" });
  await result.click();
  const latitude = page.getByLabel("Site latitude", { exact: true });
  const longitude = page.getByLabel("Site longitude", { exact: true });
  await expect(latitude).toHaveValue("");
  await expect(longitude).toHaveValue("");
  await expect(page.getByLabel("Flying site name", { exact: true })).toHaveValue("Memory Hill");
  const canvas = page.getByLabel("Flight site map", { exact: true }).locator("canvas");
  // Let the 350 ms camera movement finish before picking (a click interrupts it).
  await page.waitForTimeout(500);
  await canvas.click();
  expect(Number(await latitude.inputValue())).toBeCloseTo(45.9, 1);
  expect(Number(await longitude.inputValue())).toBeCloseTo(6.115, 1);
  await expect(page).toHaveURL(/\/upload$/);
  const flyingLat = await latitude.inputValue();
  const flyingLon = await longitude.inputValue();
  await page.getByRole("button", { name: "Landing", exact: true }).click();
  await expect(page.getByRole("button", { name: "Landing", exact: true })).toHaveAttribute("aria-pressed", "true");
  await search.fill("Annecy France");
  await search.press("Enter");
  await result.click();
  await page.waitForTimeout(500);
  await canvas.click({ position: { x: 180, y: 180 } });
  const landingLatitude = page.getByLabel("Landing latitude", { exact: true });
  const landingLongitude = page.getByLabel("Landing longitude", { exact: true });
  const landingLat = await landingLatitude.inputValue();
  const landingLon = await landingLongitude.inputValue();
  expect(Number(landingLat)).toBeCloseTo(45.9, 1);
  expect(Number(landingLon)).toBeCloseTo(6.115, 1);
  expect([landingLat, landingLon]).not.toEqual([flyingLat, flyingLon]);
  await expect(latitude).toHaveValue(flyingLat);
  await expect(longitude).toHaveValue(flyingLon);
  await expect(page.getByRole("img", { name: "Flying site pin (blue)" })).toBeAttached();
  await expect(page.getByRole("img", { name: "Landing pin (orange)" })).toBeAttached();
  await canvas.scrollIntoViewIfNeeded();
  await page.waitForTimeout(500);
  await page.screenshot({ path: "test-results/manual-landing-map-mobile.png" });
  await page.getByRole("button", { name: "Add manual flight", exact: true }).click();
  await expect(page).toHaveURL(/\/flights\/[a-z0-9]+$/);
  await page.getByRole("link", { name: "Edit flight", exact: true }).click();
  await page.getByText("Site location", { exact: true }).click();
  await expect(page.getByLabel("Site latitude", { exact: true })).toHaveValue(flyingLat);
  await expect(page.getByLabel("Site longitude", { exact: true })).toHaveValue(flyingLon);
  await expect(page.getByLabel("Landing latitude", { exact: true })).toHaveValue(landingLat);
  await expect(page.getByLabel("Landing longitude", { exact: true })).toHaveValue(landingLon);
});

test("manual flight → edit → attach a reviewed IGC, keeping one entry", async ({ page }) => {
  await signUp(page);
  await page.getByRole("main").getByRole("link", { name: "Add flight", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Add flight", exact: true })).toBeVisible();
  await page.getByLabel("Flight date", { exact: true }).fill("2024-07-12");
  await page.getByRole("spinbutton", { name: "Duration hours", exact: true }).fill("1");
  await page.getByRole("spinbutton", { name: "Duration minutes", exact: true }).fill("30");
  await page.getByLabel("Wing", { exact: true }).fill("Historic wing");
  await page.getByLabel("Flying site name", { exact: true }).fill("Memory Hill");
  await page.getByRole("combobox", { name: "XC type", exact: true }).selectOption("fai-triangle");
  await page.getByLabel("XC distance", { exact: true }).fill("45");
  await page.getByText("Site location", { exact: true }).click();
  await page.getByLabel("Site latitude", { exact: true }).fill("37.6685");
  await page.getByLabel("Site longitude", { exact: true }).fill("-122.4936");
  await page.getByRole("button", { name: "Add manual flight", exact: true }).click();
  await expect(page).toHaveURL(/\/flights\/[a-z0-9]+$/);
  const flightUrl = page.url();
  await expect(page.getByText("Manual logbook entry · no track recorded")).toBeVisible();
  await expect(page.getByLabel("Flight site map", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Go to max altitude" })).toHaveCount(0);
  await page.getByRole("link", { name: "Edit flight", exact: true }).click();
  await expect(page.getByLabel("Duration minutes", { exact: true })).toHaveValue("30");
  await page.getByLabel("Duration minutes", { exact: true }).fill("40");
  await page.getByRole("button", { name: "Save flight details" }).click();
  await expect(page).toHaveURL(flightUrl);
  await page.goto(`${flightUrl}/edit`);
  await expect(page.getByText("Drop an IGC file here", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Choose file", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Compare IGC with this entry" })).toHaveCount(0);
  await expect(page.getByLabel("IGC to attach")).toBeEnabled();
  await page.getByLabel("IGC to attach").setInputFiles({ name: "found.igc", mimeType: "application/octet-stream", buffer: Buffer.from(makeRealisticFlight().igc) });
  await expect(page.getByText("Selected: found.igc", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Compare IGC with this entry" }).click();
  await expect(page.getByRole("columnheader", { name: "From IGC" })).toBeVisible();
  await page.getByRole("button", { name: "Attach IGC and use recorded measurements" }).click();
  await expect(page).toHaveURL(flightUrl);
  await page.goto("/logbook");
  await expect(page.getByRole("status").filter({ hasText: "1 of 1 flight" })).toBeVisible();
});

test("CSV name matching, duplicate review, reported trophies, mobile layout and undo", async ({ page }) => {
  test.setTimeout(120000);
  await signUp(page);
  await page.goto("/settings");
  await page.getByRole("link", { name: "Import logbook", exact: true }).click();
  const csv = "date,duration_minutes,wing,site,xc_distance,xc_type\n2001-04-24,60,Rush4,Hill,25,open\n2001-04-24,60,Rush 4,Hill,25,open\n2001-04-25,,Rush4,Hill,30,FAI triangle";
  await expect(page.getByLabel("Choose logbook CSV")).toBeEnabled();
  await page.getByLabel("Choose logbook CSV").setInputFiles({ name: "history.csv", mimeType: "text/csv", buffer: Buffer.from(csv) });
  await page.getByRole("button", { name: "Continue to names" }).click();
  await page.getByLabel("Wings: Rush4", { exact: true }).fill("Rush 4");
  await page.getByRole("button", { name: "Review flights", exact: true }).click();
  await expect(page.getByText("May overlap:", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Discard all", exact: true }).click();
  await page.getByRole("button", { name: "Check preview", exact: true }).click();
  await expect(page.getByText("Preview checked.", { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/logbook-import-review-mobile.png", fullPage: true });
  await page.getByLabel("I have checked the dates, units, and selected flights.").check();
  await page.getByRole("button", { name: "Import 2 flights", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Your flights are in your logbook" })).toBeVisible();
  await page.getByRole("link", { name: "Open logbook", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "2 of 2 flights" })).toBeVisible();
  await expect(page.getByText("Airtime excludes 1 flight with unknown duration.")).toBeVisible();
  await expect(page.getByLabel(/Gold.*FAI triangle.*reported/)).toBeVisible();
  await page.goto("/settings/import");
  await page.getByRole("button", { name: "Undo import", exact: true }).click();
  await page.getByRole("button", { name: "Remove unchanged entries", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("2 entries removed");
  await page.goto("/logbook");
  await expect(page.getByRole("link", { name: "Add your first flight" })).toBeVisible();
});

test("recording names stay read-only and wing edits preserve historical labels and original IGC", async ({ page }) => {
  const hydrationErrors: string[] = [];
  page.on("console", message => {
    if (/hydration|hydrated/i.test(message.text())) hydrationErrors.push(message.text());
  });
  await signUp(page);
  const igc = Buffer.from(makeRealisticFlight().igc.replace("\n", "\nHFPLTPILOTINCHARGE:Recorder Friend\n"));
  await page.goto("/upload");
  await uploadFlight(page, { name: "borrowed.igc", mimeType: "application/octet-stream", buffer: igc });
  await expect(page).toHaveURL(/\/flights\/[a-z0-9]+$/);
  const flightUrl = page.url(), id = flightUrl.split("/").pop()!;
  const db = new PrismaClient();
  try {
    // Represent a correction made with the previous version of Leaf Log.
    await db.flight.update({ where: { id }, data: { pilot: "Earlier saved label" } });
    await page.goto(`${flightUrl}/edit`);
    await expect(page.getByRole("textbox", { name: /pilot/i })).toHaveCount(0);
    await expect(page.getByRole("combobox", { name: /pilot/i })).toHaveCount(0);
    await page.getByText("Recording details", { exact: true }).click();
    await expect(page.getByText("Pilot name in original IGC", { exact: true })).toBeVisible();
    await expect(page.getByText("Recorder Friend", { exact: true })).toBeVisible();
    await expect(page.getByText("Earlier saved label", { exact: true })).toBeVisible();
    await page.getByRole("textbox", { name: "Wing name", exact: true }).fill("Corrected Wing");
    await page.getByRole("button", { name: "Save wing", exact: true }).click();
    await expect(page.getByText("Saved.", { exact: true })).toBeVisible();
    const saved = await db.flight.findUniqueOrThrow({ where: { id }, include: { data: true } });
    expect(saved.pilot).toBe("Earlier saved label");
    expect(saved.glider).toBe("Corrected Wing");
    expect(Buffer.from(saved.data!.rawIgc)).toEqual(igc);
    await page.setViewportSize({ width: 390, height: 844 });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: "test-results/recording-details-mobile.png", fullPage: true });
    await page.goto("/upload");
    await uploadFlight(page, { name: "no-pilot-name.igc", mimeType: "application/octet-stream", buffer: Buffer.from(makeRealisticFlight().igc) });
    await page.getByRole("button", { name: "Keep this uploaded flight", exact: true }).click();
    await expect(page).toHaveURL(/\/flights\/[a-z0-9]+$/);
    await page.goto(`${page.url()}/edit`);
    await page.getByText("Recording details", { exact: true }).click();
    await expect(page.getByText("Pilot name in original IGC", { exact: true })).toHaveCount(0);
    await expect(page.getByRole("textbox", { name: /pilot/i })).toHaveCount(0);
    await expect(page.getByText("Unknown pilot", { exact: true })).toHaveCount(0);
    await expect(page.getByRole("textbox", { name: "Wing name", exact: true })).toBeEnabled();
    expect(hydrationErrors).toEqual([]);
  } finally { await db.$disconnect(); }
});
